### PR TITLE
make use of include_failed_variations flag in VariationFeatureAdaptor…

### PR DESCRIPTION
**Pull request by ima23**
… and fixed typo

### CODE REVIEW

**Comment by ens-lgil** [comment]
Should it go into the release/92 ?

**Comment by ima23** [comment]
@ens-lgil: thanks for checking. It's not urgent, would be nice 92 but 93 is also ok.

**Comment by at7** [comment]
It would be worth checking why VariationFeatureAdaptor::_default_where_clause is not setting the failed status.

**Comment by at7** [comment]
I wouldn't worry about why _default_where_clause is not used. It is only relevant for the fetch_all methods which are not useful for the amount of data we have anyway. You could call VariationFeatureAdaptor::fetch_all_by_Slice_constraint from VariationFeatureAdaptor::fetch_all and VariationFeatureAdaptor::fetch_all_somatic. But not necessary in my opinion.

**Comment by at7** [comment]
This needs to go to master and release/92

**Comment by ima23** [comment]
Closed for a cleaner PR

**Comment by ima23** [comment]
The final tests are in PR #141. The solution to the discrepancy was to clear the cache or not use any caching. Default mode uses a cache.

**Pull request closed without merging**
