### PR TITLE
add conservation files

### PR DESCRIPTION
**Pull request by at7**
Adding all conservation score files for our variation species for release/96

### CODE REVIEW

**Comment by ens-lgil** [comment]
Does it mean that we will have to update it every release ?
It's pointing at the `release-96` FTP directory.

**Comment by at7** [comment]
Yes. But the compara team will very likely increase the number of species included in each alignment every release. Using the release version will allow for backwards compatibility, using the correct alignment for the given release. In the future the vcf_config file will be created automatically.

**Comment by ens-lgil** [comment]
An other remark: should we use a different `id` for each entry ?
So far they are all the same.
e.g.: 
```
"id": "88_mammals.gerp_conservation_score",
"species": "bos_taurus",
```
Could become:
```
"id": "88_mammals.gerp_conservation_score_cow",
"species": "bos_taurus",
```

**Comment by at7** [comment]
I don't think this is necessary. It will already be filtered by the species key.

**Comment by ens-lgil** [comment]
Ok fine!

**Comment by ens-lgil** [comment]
Merged into `master` and `release/96`

**Pull request merged**
