### PR TITLE
Updating regulation effect params

### PR DESCRIPTION
**Pull request by jamie-m-a**
Removing use of experimentally validated motif features as now defunct.
Extended time (and a bit of extra memory) for the last analysis to avoid running out of time for human.

### CODE REVIEW

**Comment by dglemos** [comment]
@jamie-m-a there is a PR to remove the option https://github.com/Ensembl/ensembl-variation/pull/1133
Also, we have this merged PR to add the long queue: https://github.com/Ensembl/ensembl-variation/pull/1129 (I can cherry pick to 114)

**Comment by jamie-m-a** [comment]
Ah sorry @dglemos - feel free to close this one @nakib103 if not needed.

**Comment by dglemos** [comment]
Changes to the long queue were added to the existing PR https://github.com/Ensembl/ensembl-variation/pull/1133/commits/69002ba510800ba638d04d4fd1dd1b1d66716801

**Comment by nakib103** [comment]
Thanks @jamie-m-a , @dglemos , I will close this PR.

**Pull request closed without merging**
