### PR TITLE
Change to FastaSequence.pm to allow fetching softmasked sequence from file

### PR DESCRIPTION
**Pull request by fergalmartin**
Updated code to allow a flag to preserve any softmasking in the fasta file when fetching sequence. This is to avoid querying the repeat_feature table via the API as asking for masked sequence incurs a join between repeat_feature and repeat_consensus that becomes expensive when there are many jobs running in parallel. The flag is passed through into the overriden ->seq into the _raw_seq subroutine. The code in _raw_seq has been slightly refactored to to the uc call after fetching the sequence, unless the preserve_masking flag has been passed. Example usage would be: my  = ->(undef,undef,undef,1)

### CODE REVIEW

**Comment by ens-lgil** [comment]
@fergalmartin, would it be possible to add a basic test to cover your changes in https://github.com/Ensembl/ensembl-variation/blob/master/modules/t/fastaSequence.t before the branching to 97 ?
Thanks.

**Comment by fergalmartin** [comment]
@ima23, @ens-lgil I have asked @ens-carlos to look into putting in a test by Monday.

**Comment by ens-carlos** [comment]
Would it be possible to modify the existing $Bin\/testdata/vep-cache/homo_sapiens/78_GRCh38/test.fa.gz file to lower case some of its bases on a region not used in any of the current tests or to have a softmasked version of any chromosome so I can point to it in the corresponding tests?

**Comment by ima23** [comment]
@ens-carlos could you please add a small masked test fasta file in https://github.com/Ensembl/ensembl-variation/tree/master/modules/t/testdata? It's best to keep the vep-cache test data as it is. 
Thanks.

**Comment by ens-carlos** [comment]
Yes, no problem. Thank you.

**Comment by ens-carlos** [comment]
I've created a separate pull request to add the test.

**Pull request merged**
