### PR TITLE
Adding an explanation of the function

### PR DESCRIPTION
**Pull request by dbolser-ebi**
For people (idiots) like me.

### CODE REVIEW

**Comment by ens-lgil** [comment]
Hi Dan,
Sarah just added a documentation about this method:
https://github.com/Ensembl/ensembl-variation/commit/6e850c70a643bab0089642e269a6a2c552107739

**Comment by sarahhunt** [comment]
@dbolser-ebi - are you happy with the text I added?

**Comment by dbolser-ebi** [comment]
Yup

**Comment by sarahhunt** [comment]
Great!

**Pull request closed without merging**
