### PR TITLE
Update json configuration for new genotype data

### PR DESCRIPTION
**Pull request by nakib103**
We are adding new genotype data from EVA vcf - 
https://www.ebi.ac.uk/eva/?eva-study=PRJEB44919 

In this process we need to update the vcf file information in the vcf_config.json file. The genotype data is tested on sandbox - 

e.g. - http://wp-np2-11.ebi.ac.uk:7070/Gallus_gallus/Variation/Population?db=core;r=1:196051926-196053237;v=rs739477247;vdb=variation;vf=4893594)

### CODE REVIEW

**Comment by jamie-m-a** [comment]
Hi @nakib103 PR looks fine, but can you provide a fresh sandbox link, old one seems to be broken.

**Comment by nakib103** [comment]
> http://wp-np2-11.ebi.ac.uk:7070/Gallus_gallus/Variation/Population?db=core;r=1:196051926-196053237;v=rs739477247;vdb=variation;vf=4893594

@jamie-m-a , can you check now with the same link.

**Comment by jamie-m-a** [comment]
Chicken and dog look ok, but I cant see any variants for salmon.

**Comment by nakib103** [comment]
> Chicken and dog look ok, but I cant see any variants for salmon.

The current examples may not work as assembly change. This wider view shows data - http://wp-np2-11.ebi.ac.uk:7070/Salmo_salar/Location/View?r=1:1000000-2000000;db=core

**Review by jamie-m-a — APPROVED** [review]
Looks good

**Pull request merged**
