### PR TITLE
Feature/genome wide scores updates

### PR DESCRIPTION
**Pull request by at7**
Some required updates which came apparent while doing web display updates.

### CODE REVIEW

**Comment by at7** [comment]
I just noticed that I deleted vervet from the vcf_config file. I will add it back in a separate PR.

**Comment by sarahhunt** [comment]
This looks fine - we can merge when there's a PR to add vervet back to the vcf_config file

**Comment by ens-lgil** [comment]
Can't we add a new commit with vervet in this PR instead ?

**Comment by at7** [comment]
I had a merge conflict and my local vcf_config is out of sync with the remote PR. I will resolve it separately.

**Comment by at7** [comment]
I just updated the file through git's interface. It's as easy as that. I will merge the PR now.

**Comment by at7** [comment]
merged to master and release/96

**Pull request merged**
