### PR TITLE
Prevent shifting if no_shift is undefined

### PR DESCRIPTION
**Pull request by aparton**

### CODE REVIEW

**Comment by at7** [comment]
If ( defined($args{'-no_shift'}) && !$args{'-no_shift'} ) is true does that mean we shift?

**Comment by aparton** [comment]
If --no_shift is set to 1, then we shouldn't shift. If no shift is set to 0, then we should shift. 

The change should handle the undefined case. Previously, if it was undefined, this would trigger shifting code. We want to not shift by default in that case

**Comment by at7** [comment]
We shouldn't pass a value to --no_shift. no_shift means no shift. --no_shift 0 doesn't make sense unfortunately. Is this something a VEP user needs to decide? Or is this an internal argument?

**Comment by at7** [comment]
Some tests in variant_effect.t fail

**Comment by ima23** [comment]
merged to `release/100` and `master`

**Pull request merged**
