### PR TITLE
Revert to old update vf mode for speed

### PR DESCRIPTION
**Pull request by jamie-m-a**
Re: ENSVAR-5938

Has been run successfully. Can compare the update vf code to code in 107 or earlier to confirm just reverting.

### CODE REVIEW

**Review by nuno-agostinho — CHANGES_REQUESTED** [review]
Hi @jamie-m-a, the changes seem fine compared to [release 107](https://github.com/Ensembl/ensembl-variation/blob/release/107/modules/Bio/EnsEMBL/Variation/Pipeline/UpdateVariationFeature.pm).

Just left a small comment. Thanks!

**Comment by jamie-m-a** [comment]
> Hi @jamie-m-a, the changes seem fine compared to [release 107](https://github.com/Ensembl/ensembl-variation/blob/release/107/modules/Bio/EnsEMBL/Variation/Pipeline/UpdateVariationFeature.pm).
> 
> Just left a small comment. Thanks!

Agreed, removed irrelevant comment.

**Review by nuno-agostinho — APPROVED** [review]
Looks good, thanks @jamie-m-a!

**Comment by nuno-agostinho** [comment]
Merged to `main` and `release/111`.

**Pull request merged**
