### PR TITLE
Update the BioPerl directory

### PR DESCRIPTION
**Pull request by ens-lgil**

### CODE REVIEW

**Comment by at7** [comment]
So what happened here? Has bioperl removed a release branch?

**Comment by ens-lgil** [comment]
This is related to this PR in ensembl-production: https://github.com/Ensembl/ensembl-production/pull/214
Basically the BioPerl path we put in PERL5LIB was wrong (outdated) so Bio-DB-HTS didn't find the BioPerl installation , therefore it tried to download the BioPerl version `1.7.2`, which is quite different from the `1.6.924` and it caused an issue with the rest of the installation

**Comment by at7** [comment]
That makes sense now. Thank you!

**Comment by ens-lgil** [comment]
Wrong commit

**Pull request closed without merging**
