### PR TITLE
Update variation consequence pipeline

### PR DESCRIPTION
**Pull request by dglemos**

### CODE REVIEW

**Review by nuno-agostinho — APPROVED** [review]
Changes seem appropriate. 👍

Should we also update [AncestralAlleles_conf.pm](https://github.com/Ensembl/ensembl-variation/blob/master/modules/Bio/EnsEMBL/Variation/Pipeline/AncestralAlleles/AncestralAlleles_conf.pm) from using eHive 2.5 to 2.6?

**Comment by dglemos** [comment]
good spot @nuno-agostinho, I've updated that one too.

**Review by nuno-agostinho — APPROVED** [review]
No problem! Great, seems ready to merge to me.

**Comment by olaaustine** [comment]
Merged into master and release/107 on 13 April

**Pull request merged**
