### PR TITLE
Test for fetching softmasked sequence

### PR DESCRIPTION
**Pull request by ens-carlos**
Test for "Change to FastaSequence.pm to allow fetching softmasked sequence from file"

### CODE REVIEW

**Comment by ima23** [comment]
Thanks for the test sample @ens-carlos, can you please place the test file out side of the `vep-cache` test data folder and move it in the `t/testdata`, see https://github.com/Ensembl/ensembl-variation/pull/330#issuecomment-475259511.

**Comment by ima23** [comment]
On further thought I can move the file after check pass and I merge it, so no further action required for now @ens-carlos. Thanks.

**Comment by ens-carlos** [comment]
The check will only suceed once Fergal's pull request has been accepted.

**Comment by ima23** [comment]
@ens-carlos : Travis fails as it seems the fastaSequence.t test(https://github.com/Ensembl/ensembl-variation/pull/344/files#diff-982e1ffb78216486a81983ca26d621d2R86) expects `AACGTCGCGCG` but got `aaCGTcgcgcg `. Can you have a look please? Thanks.

**Comment by ens-carlos** [comment]
It looks fine now. Thanks Irina.

**Pull request merged**
