### PR TITLE
Remove flanking seq table

### PR DESCRIPTION
**Pull request by ima23**

### CODE REVIEW

**Comment by sarahhunt** [comment]
If you look at the history, EnsemblVariationSchema.txt and remove_wrong_variations.sql haven't been updated since 2007 and 2010. They are no longer used, so did not need updating. We need to trawl for obsolete code in coming months.

**Comment by sarahhunt** [comment]
For import_vcf, 
- flank can be removed from the config at line 216
- the flanks option should be removed from the GetOptions list
- the upstream/downstream setting at 1932 isn't needed

**Comment by ima23** [comment]
Thanks @sarahhunt for checking. I have removed the updated to the 2 files that have not been changed for a while. Current PR contains now only the  previous + mentioned changes to import_vcf.pl

**Comment by sarahhunt** [comment]
All of the upstream/downstream flank setting code from comment 'add in some hacky stuff so flanking sequence gets written' can be removed

**Comment by ima23** [comment]
Thanks @sarahhunt for checking. I've removed that old section in the next commit.

**Pull request merged**
