### PR TITLE
Update remapping pipeline

### PR DESCRIPTION
**Pull request by at7**
A lot of changes to the remapping pipeline. Most of the changes are from last year. I finally found time to create a PR. The changes should make it easier together with the [documentation](https://www.ebi.ac.uk/seqdb/confluence/display/EV/Remapping+pipeline) to run remapping pipelines. Let me know if you find anything obviously wrong. Otherwise we can schedule code reviews and I can talk you through the steps.

### CODE REVIEW

**Comment by ens-lgil** [comment]
I am not sure I can review all of these changes!
Do the different remapping pipelines share components/modules ?
I wonder if this would be easier for maintenance (and understanding) to have the different types of remapping pipelines in different subdirectories

**Comment by ens-lgil** [comment]
Do you need to do minor changes/fixes/cleanings regarding the code review on monday ?

**Comment by at7** [comment]
I updated all issues which I came across during the code review on Monday.

**Comment by at7** [comment]
We can now call the pipeline with:
HIVE_SRV=HIVE_SRV=$host-$user
init_pipeline.pl Bio::EnsEMBL::Variation::Pipeline::Remapping::RemappingVariationFeature_conf \
$($HIVE_SRV details hive) \
Example is on the remapping documentation page.
I copied that from how production updated our data dump pipeline. Something to adopt for other pipelines too.

**Comment by helensch** [comment]
The header information in the *.pm is different to other pipelines. 
In other pipelines the License is in POD and the link to the helpdesk is a link.
In the remapping pipeline some *.pm files the license is a comment and the email for the helpdesk is heldesk.org.

**Comment by helensch** [comment]
Some of the copyright dates in the *.pm need to be updated from 2017 to 2018

**Comment by at7** [comment]
Thank you @helensch. I copied a header from the current release. I updated the year from 2017 to 2018.

**Pull request merged**
