### PR TITLE
adding attached VCf for wheat

### PR DESCRIPTION
**Pull request by gnaamati**
Adding remote VCF files for wheat variation

### CODE REVIEW

**Comment by gnaamati** [comment]
Hi Anja, I tested this against the variation API but will do so again (the link to the FTP changed). This also works on my sandbox.
I am trying to get the LD display to work for release 100, I assumed that the variation handover date was the same for PRs. If not I can put this in postreleasefix/100 or if this is an issue do this in 101, I'm not certain the LD will work for 100.
I will also remove strict_name_match and sample_prefix.

**Comment by gnaamati** [comment]
This works against the variation API.

**Comment by at7** [comment]
If this should go into 100 can you please do a PR against postreleasefix/100? Thanks

**Comment by at7** [comment]
@gnaamati Could you please let us know if this PR is still needed?

**Pull request closed without merging**
