### PR TITLE
Some (more) HGVS updates

### PR DESCRIPTION
**Pull request by nakib103**
- [ENSVAR-5765](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5765): VEP incorrectly term HGVS type as ins when it should be dup. This happens when the variant strand is in reverse and transcript strand is forward. 
- [ENSVAR-5625](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5625): We are clipping alleles when the HGVS type is `delins` and update type and co-ordinates. We are not considering type changing to `dup` currrently. Related issue - https://github.com/Ensembl/ensembl-vep/issues/500 
- [ENSVAR-2140](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2140): Add new argument `--hgvsp_use_prediction` to output HGVSp in prediction format. Related issue - https://github.com/Ensembl/ensembl-vep/issues/861

_Test data are in the respective JIRA tickets_

### CODE REVIEW

**Review by nuno-agostinho — CHANGES_REQUESTED** [review]
Hey @nakib103, thanks for the changes! Tested based on the PR examples and everything seems to be working.

I just have a small comment, but everything else seems fine!

**Comment by nuno-agostinho** [comment]
Also, is this for 110 or 111?

**Comment by nakib103** [comment]
We already branched for 110, so it is for 111.

**Review by nuno-agostinho — APPROVED** [review]
Looks good to me, thanks @nakib103!

**Comment by nuno-agostinho** [comment]
Merged to branches `release/110`, `postreleasefix/110`, `release/111` and `postreleasefix/111`.

**Pull request merged**
