### PR TITLE
Trigger depedent builds on vep and rest

### PR DESCRIPTION
**Pull request by avullo**
The usual Travis CI build is altered so that another stage runs sequentially after the matrix build. You will now see two stages on the Travis interface: "Test" (matrix build) and "Trigger_dependent_build".
The new stage makes use of the Travis CI API to automatically trigger a build on the dependent repos. This does not occur in case another API triggered build is running or has run within the last hour.

### CODE REVIEW

**Comment by avullo** [comment]
For information, build 1574 is now running with two sequential stages. Stage 2 will stop because it's programmed not to run on PRs.

**Comment by ens-lgil** [comment]
Looks fine for me

**Comment by sarahhunt** [comment]
Thanks @avullo !

**Comment by avullo** [comment]
@sarahhunt you're welcome, glad it's considered useful :+1:

**Pull request merged**
